// ==================== SHARED PRODUCT DATA ====================
const categoryLabels = {
    'chicken-cold-cuts': 'Chicken Cold Cuts',
    'pork-cold-cuts': 'Pork Cold Cuts',
    'pork-cured-fermented': 'Pork Cured & Fermented',
    'raw-pork': 'Raw Pork',
    'turkey-cold-cuts': 'Turkey Cold Cuts',
    'duck-cold-cuts': 'Duck Cold Cuts',
    'lamb-cold-cuts': 'Lamb Cold Cuts',
    'goat-meat': 'Goat Meat',
    'imported-seafood': 'Imported Seafood',
    'indian-seafood': 'Indian Seafood',
    'japanese-groceries': 'Japanese Groceries',
    'japanese-frozen-seafood': 'Japanese Frozen Seafood',
    'golden-wrap': 'Golden Wrap',
    'sakura-frozen': 'Sakura Frozen'
};

// Compact: [classification, name, weight, price] or [classification, name, weight, price, country]
const productData = {
    'chicken-cold-cuts': {
        img: 'pictures/chicken_category.png',
        country: 'India',
        items: [
            ['Bacon', 'Chicken Bacon', '1 kg', 450],
            ['Frankfurter', 'Chicken Chorizo Sausage Jumbo', '1 kg', 520],
            ['Frankfurter', 'Chicken Frankfurter Jumbo', '1 kg', 480],
            ['Ham', 'Chicken Sandwich Ham', '1 kg', 420],
            ['Ham', 'Chicken Smoked Ham', '1 kg', 460],
            ['Kebab', 'Chicken Seekh Kebab Plain', '1 kg', 380],
            ['Kebab', 'Chicken Seekh Kebab Lahsooni', '1 kg', 400],
            ['Kebab', 'Chicken Seekh Kebab Punjabi', '1 kg', 400],
            ['Kebab', 'Chicken Seekh Kebab Hot & Spicy', '1 kg', 410],
            ['Mortadella', 'Chicken Mushroom Lyoner', '1.2-2 kg', 650],
            ['Mortadella', 'Chicken Mortadella Paprika', '1.2-2 kg', 680],
            ['Mortadella', 'Chicken Mortadella Pistachio Roll', '1.2-2 kg', 750],
            ['Mortadella', 'Chicken Mortadella Smoked Roll', '1.2-2 kg', 700],
            ['Mortadella', 'Chicken Mortadella Spicy', '1.2-2 kg', 680],
            ['Mortadella', 'Chicken Lyoner Mortadella Plain', '1.2-2 kg', 620],
            ['Mortadella', 'Chicken Lyoner Black Pepper', '1.2-2 kg', 640],
            ['Mortadella', 'Chicken Lyoner Green Olives', '1.2-2 kg', 660],
            ['Mortadella', 'Chicken Lyoner Paprika', '1.2-2 kg', 640],
            ['Pepperoni', 'Chicken Pepperoni Sliced', '1 kg', 520],
            ['Processed', 'Smoked Chicken Breast', '1 kg', 550],
            ['Processed', 'Smoked Whole Chicken', '1 kg', 650],
            ['Processed', 'Chicken Tandoori Breast', '1 kg', 500],
            ['Processed', 'Chicken Herbs Breast', '1 kg', 520],
            ['Processed', 'Chicken Tikka Tandoori', '1 kg', 480],
            ['Processed', 'Chicken Tikka Malai', '1 kg', 480],
            ['Processed', 'Chicken Tikka Hariyali', '1 kg', 470],
            ['Processed', 'Chicken Tikka Achari', '1 kg', 470],
            ['Processed', 'Chicken Meatballs', '1 kg', 420],
            ['Salami', 'Chicken Salami Plain', '1 kg', 480],
            ['Salami', 'Chicken Salami Spicy Masala', '1 kg', 500],
            ['Salami', 'Chicken Salami Black Pepper', '1 kg', 500],
            ['Salami', 'Chicken Salami With Jalapeno', '1 kg', 520],
            ['Salami', 'Chicken Salami With Cheese', '1 kg', 540],
            ['Sausage', 'Chicken Premium Sausage 3"', '1 kg', 450],
            ['Sausage', 'Chicken Breakfast Sausage', '1 kg', 380],
            ['Sausage', 'Chicken Breakfast Cocktail Sausage', '1 kg', 360],
            ['Sausage', 'Chicken Classic Sausage', '1 kg', 350],
            ['Sausage', 'Chicken Classic Cocktail Sausage', '1 kg', 340],
            ['Sausage', 'Chicken Smoked Sausage', '1 kg', 400],
            ['Sausage', 'Chicken Bockwurst Sausage Jumbo', '1 kg', 480],
            ['Sausage', 'Chicken Bratwurst Sausage Jumbo', '1 kg', 490],
            ['Sausage', 'Chicken Cheese & Jalapeno Sausage', '1 kg', 460],
            ['Sausage', 'Chicken Cheese Jalapeno Smoked Cocktail', '1 kg', 470],
            ['Sausage', 'Chicken Parsley Sausage', '1 kg', 420],
            ['Sausage', 'Chicken Cheese & Onion Sausage', '1 kg', 440],
            ['Sausage', 'Chicken Chiplota Sausage', '1 kg', 380]
        ]
    },
    'pork-cold-cuts': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Bacon', 'Pork Streaky Bacon', '1 kg', 550],
            ['Bacon', 'Pork Smoked Bacon', '1 kg', 580],
            ['Bacon', 'Pork Breakfast Bacon', '1 kg', 520],
            ['Bacon', 'Pork Bacon Sliced Bits', '1 kg', 500],
            ['Bacon', 'Imported Pork Streaky Bacon', '1 kg', 650],
            ['Frankfurter', 'Pork Frankfurter Jumbo', '1 kg', 520],
            ['Ham', 'Pork Sandwich Ham Slice', '1 kg', 450],
            ['Ham', 'Pork Smoked Ham Slice', '1 kg', 480],
            ['Ham', 'Pork Black Forest Ham Log', '1.2-2 kg', 850],
            ['Ham', 'Pork Heritage Ham Log', '1.2-2 kg', 800],
            ['Ham', 'Pork Honey Glazed Ham Log', '1.2-2 kg', 820],
            ['Ham', 'Pork Honey Ham Log', '1.2-2 kg', 780],
            ['Ham', 'Pork Sandwich Ham Log', '1.2-2 kg', 750],
            ['Meatloaf', 'Pork Bavarian Meatloaf', '1.2-2 kg', 700],
            ['Meatloaf', 'Pork Leberkasse Meatloaf', '1.2-2 kg', 720],
            ['Mortadella', 'Pork Mortadella Pistachio Smoked', '1.2-2 kg', 680],
            ['Mortadella', 'Pork Mortadella Plain Log', '1.2-2 kg', 620],
            ['Pepperoni', 'Pork Pepperoni', '1 kg', 550],
            ['Salami', 'Pork Salami', '1 kg', 580],
            ['Sausage', 'Pork Premium Sausage 3"', '1 kg', 480],
            ['Sausage', 'Pork Sausage', '1 kg', 400],
            ['Sausage', 'Pork Cocktail Sausage', '1 kg', 380],
            ['Sausage', 'Pork Kransky Sausage', '1 kg', 520],
            ['Sausage', 'Pork Krakauer Sausage', '1 kg', 540],
            ['Sausage', 'Pork Bockwurst Sausage Jumbo', '1 kg', 500],
            ['Sausage', 'Pork Bratwurst Sausage Jumbo', '1 kg', 510],
            ['Sausage', 'Pork Chorizo Sausage Jumbo', '1 kg', 550],
            ['Sausage', 'Pork Kielbasa Sausage', '1 kg', 530],
            ['Sausage', 'Pork Curly Sicilian Sausage', '1 kg', 560],
            ['Sausage', 'Pork Cumberland Sausage', '1 kg', 520]
        ]
    },
    'pork-cured-fermented': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Imported', 'Pork Guanciale', '1-1.5 kg', 1800],
            ['Imported', 'Pork Pepperoni Imported', '1 kg', 950],
            ['Imported', 'Pork Chorizo Imported', '1 kg', 900],
            ['Imported', 'Pork Nduja Sausages', '200 g', 650],
            ['Imported', 'Pork Diavolette Salsiccia', '1 kg', 1100],
            ['Imported', 'Pork Black Forest Imported', '1-1.5 kg', 1600],
            ['Imported', 'Pork Salami Milano', '1-1.5 kg', 1400],
            ['Imported', 'Pork Milano Salami', '1-1.5 kg', 1350],
            ['Imported', 'Pork Honey Glazed Ham Imported', '1-1.5 kg', 1500],
            ['Imported', 'Pork Goan Chorizo Sausage', '1-1.5 kg', 1200],
            ['Imported', 'Parma Ham Prosciutto', '1-1.5 kg', 2200],
            ['Imported', 'Parma Ham Debone Prosciutto', '1-1.5 kg', 2100]
        ]
    },
    'raw-pork': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Raw', 'Pork Belly Regular With Skin', '4-6 kg', 450],
            ['Raw', 'Pork Belly Prime Without Skin', '4-6 kg', 500],
            ['Raw', 'Pork Shoulder Boneless Meat', '1 kg', 420],
            ['Raw', 'Pork Chop With Bone', '1 kg', 440],
            ['Raw', 'Pork Spare Ribs', '1.2-1.5 kg', 480],
            ['Raw', 'Pork Leg Boneless', '1 kg', 400],
            ['Raw', 'Pork Neck Boneless', '1 kg', 380],
            ['Raw', 'Pork Tenderloin', '200-300 g', 350],
            ['Raw', 'Pork Knuckle', '1 kg', 320],
            ['Raw', 'Pork Raw Boneless', '1 kg', 380],
            ['Raw', 'Pork Shoulder Butt Boneless', '1 kg', 400],
            ['Raw', 'Pork Loin', '1 kg', 440],
            ['Raw', 'Pork Trotters', '1 kg', 250],
            ['Raw', 'Pork Head', 'Per Pc', 300],
            ['Raw', 'Pork Carcass', 'Per Pc', 280],
            ['Raw', 'Pork Mince', '1 kg', 350],
            ['Raw', 'Pork Liver', '1 kg', 200],
            ['Raw', 'Pork Lungs', '1 kg', 180],
            ['Raw', 'Pork Heart', '1 kg', 200],
            ['Raw', 'Pork Blood', '1 kg', 150],
            ['Raw', 'Pork Stomach', '1 kg', 220],
            ['Raw', 'Pork Fat', '1 kg', 180],
            ['Raw', 'Pork Hocks', '1 kg', 300],
            ['Raw', 'Pork Shank', '1 kg', 350],
            ['Raw', 'Pork Tongue', '1 kg', 280],
            ['Raw', 'Pork Thigh Boneless', '1 kg', 400],
            ['Raw', 'Suckling Pig Small', '5-6 kg/pc', 5000],
            ['Raw', 'Suckling Pig Large', '10-16 kg/pc', 8500]
        ]
    },
    'turkey-cold-cuts': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Ham', 'Turkey Ham Block', '1.2-2 kg', 750],
            ['Bacon', 'Turkey Rashers', '1 kg', 550],
            ['Salami', 'Turkey Salami', '2 kg', 680],
            ['Sausage', 'Turkey Sausage', '2 kg', 600],
            ['Raw', 'Whole Turkey', '5-6 kg/pc', 3500],
            ['Ham', 'Turkey Pastrami Style Slice', '1.2-2 kg', 850],
            ['Mortadella', 'Turkey Mortadella', '1.2-2 kg', 700],
            ['Mortadella', 'Turkey Mortadella Pistachio', '1.2-2 kg', 780],
            ['Sausage', 'Turkey Chorizo Sausage', '1 kg', 580],
            ['Frankfurter', 'Turkey Frankfurter', '1 kg', 520],
            ['Processed', 'Smoked Turkey Breast', '1 kg', 650],
            ['Processed', 'Smoked Turkey Leg', '1 kg', 600],
            ['Raw', 'Raw Turkey Curry Cut', '1 kg', 480]
        ]
    },
    'duck-cold-cuts': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Raw', 'Duck Raw Breast', '1 kg', 850],
            ['Raw', 'Duck Whole', '2-2.5 kg', 1500],
            ['Processed', 'Duck Breast Smoked', '1 kg', 1200],
            ['Raw', 'Duck Leg Raw', '1 kg', 750],
            ['Processed', 'Duck Leg Smoked', '1 kg', 950],
            ['Sausage', 'Duck Sausage', '1 kg', 700]
        ]
    },
    'lamb-cold-cuts': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Pepperoni', 'Lamb Pepperoni', '1 kg', 650],
            ['Sausage', 'Lamb Kabana Sausage', '1 kg', 580],
            ['Sausage', 'Lamb Merguez Sausage', '1 kg', 600],
            ['Kebab', 'Mutton Seekh Kebab', '1 kg', 550],
            ['Processed', 'Mutton Meatball', '1 kg', 500],
            ['Mince', 'Raw Mutton Mince', '1 kg', 620]
        ]
    },
    'goat-meat': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Goat Meat', 'Goat Meat Curry Cut', '2 kg', 850],
            ['Goat Meat', 'Goat Meat Boneless', '2 kg', 900],
            ['Goat Meat', 'Goat Meat Mince', '2 kg', 880],
            ['Goat Meat', 'Goat Meat Chops', '2 kg', 920],
            ['Goat Meat', 'Goat Leg', '900g-1.2 kg', 750]
        ]
    },
    'imported-seafood': {
        img: 'pictures/landing_img2.png',
        country: 'Norway',
        items: [
            ['Seafood', 'Salmon Fillet Raw', '1-1.5 kg', 2800, 'Norway'],
            ['Seafood', 'Smoked Salmon Fillet', '1-1.5 kg', 3200, 'Norway'],
            ['Seafood', 'Scallops 10/20 Count', '1 kg', 2500, 'USA'],
            ['Seafood', 'Green Half Shell Mussels', '1 kg', 1200, 'New Zealand'],
            ['Seafood', 'Black Half Shell Mussels', '1 kg', 1100, 'USA'],
            ['Seafood', 'John Dory Fillet', '1 kg', 1800, 'Vietnam'],
            ['Seafood', 'Seabass Chilean Whole', '4-5 kg', 3500, 'Chile'],
            ['Seafood', 'Chilean Seabass Fillet', '1-1.5 kg', 3200, 'Chile'],
            ['Seafood', 'Black Cod Whole Gutted', '4-5 kg', 3000, 'USA'],
            ['Seafood', 'Whole Salmon Gutted', '4-5 kg', 2600, 'Norway'],
            ['Seafood', 'Soft Shell Crab', '1 kg', 1800, 'Vietnam'],
            ['Seafood', 'Crab Stick', '1 kg', 800, 'Singapore'],
            ['Seafood', 'Saku Tuna', '500 g', 1500, 'Vietnam'],
            ['Seafood', 'Imported Basa', '1 kg', 600, 'Vietnam'],
            ['Seafood', 'Hamachi Fillet', '1-1.5 kg', 3500, 'Japan'],
            ['Seafood', 'Tobiko Caviar Black', '500 g', 2800, 'Japan'],
            ['Seafood', 'Tobiko Caviar Orange', '500 g', 2800, 'Japan'],
            ['Seafood', 'Tobiko Caviar Green', '500 g', 2800, 'Japan']
        ]
    },
    'indian-seafood': {
        img: 'pictures/landing_img2.png',
        country: 'India',
        items: [
            ['Indian', 'Indian Basa', '5 pcs', 550],
            ['Imported', 'Indian Basa Imported', '5 pcs', 600],
            ['Indian', 'Tilapia Fish Fillets', '5-7 pcs', 500],
            ['Indian', 'Cuttle Fish', '25-30 pcs/kg', 650],
            ['Indian', 'Whole Frozen Squid 10/15', '10-15 pcs', 700],
            ['Indian', 'Squid Tubes 25/30', '25-30 pcs/kg', 750],
            ['Indian', 'Squid Rings', '1 kg', 680],
            ['Indian', 'Seer Fish Surmai Steaks 6/7', '6-7 pcs', 900],
            ['Indian', 'Seer Fish Surmai Steaks 7/8', '7-8 pcs', 850],
            ['Indian', 'Seer Fish Surmai Steaks 9/10', '9-10 pcs', 800],
            ['Indian', 'Seer Fish Surmai Steaks 11/15', '11-15 pcs', 750],
            ['Indian', 'Seer Fish Surmai Half Cut 16/18', '16-18 pcs', 700],
            ['Indian', 'Seer Fish Surmai Curry Cut', '20-22 pcs', 680],
            ['Indian', 'Pompharate 100/200', '6-7 pcs', 500],
            ['Indian', 'Pompharate 200/300', '4 pcs', 600],
            ['Indian', 'Crab Meat', '1 kg', 1200],
            ['Indian', 'Crab Sticks', '64 pcs', 800],
            ['Indian', 'Crab Claw', '32 pcs', 1000],
            ['Indian', 'Crab Chunks', '1 kg', 1100],
            ['Prawns', 'Vannamei PD 41/50', '1 kg', 600],
            ['Prawns', 'Vannamei PD 51/60', '1 kg', 550],
            ['Prawns', 'Vannamei PD 61/70', '1 kg', 500],
            ['Prawns', 'Vannamei PD 16/20', '1 kg', 900],
            ['Prawns', 'Vannamei PD 21/25', '1 kg', 850],
            ['Prawns', 'Vannamei PD 26/30', '1 kg', 800],
            ['Prawns', 'Vannamei PD 31/40', '1 kg', 700],
            ['Prawns', 'Vannamei PDTO 8/12', '1 kg', 1000],
            ['Prawns', 'Vannamei PDTO 13/15', '1 kg', 950],
            ['Prawns', 'Vannamei PDTO 16/20', '1 kg', 900],
            ['Prawns', 'Vannamei PDTO 21/25', '1 kg', 850],
            ['Prawns', 'Vannamei PDTO 26/30', '1 kg', 800],
            ['Prawns', 'Vannamei PDTO 31/40', '1 kg', 700],
            ['Prawns', 'Vannamei PDTO 41/50', '1 kg', 650],
            ['Lobster', 'Lobster A Grade 300-400g', '300-400 g', 2500],
            ['Lobster', 'Lobster A Grade 400-1000g', '400g-1 kg', 3500],
            ['Pomfret', 'Black Pomfret 500g Up', '500g+', 1200],
            ['Pomfret', 'Silver Pomfret 300g Up', '300g+', 1400],
            ['Pomfret', 'Silver Pomfret 200-300g', '200-300 g', 1200],
            ['Pomfret', 'Silver Pomfret 100-200g', '100-200 g', 1000]
        ]
    },
    'japanese-groceries': {
        img: 'pictures/landing_img2.png',
        country: 'Japan',
        items: [
            ['Bubble Tea', 'Popping Boba All Flavors', '3.2 kg', 1800, 'Taiwan'],
            ['Bubble Tea', 'Tapioca Pearl', '3 kg', 1200, 'Taiwan'],
            ['Powder', 'Taro Powder', '1 kg', 800, 'Taiwan'],
            ['Powder', 'Thai Tea Powder', '1 kg', 750, 'Taiwan'],
            ['Powder', 'Hong Kong Milk Tea Powder', '1 kg', 780, 'Taiwan'],
            ['Syrup', 'Black Sugar Syrup', '2.5 kg', 950, 'Taiwan'],
            ['Topping', 'Composite Jelly Topping', '3.8 kg', 1100, 'Taiwan'],
            ['Powder', 'Cheese Cream Powder', '1 kg', 900, 'Taiwan'],
            ['Powder', 'Red Velvet Powder', '1 kg', 850, 'Taiwan'],
            ['Powder', 'Belgium Chocolate Powder', '1 kg', 900, 'Taiwan'],
            ['Rice', 'Japanese Rice Kokuho', '22.7 kg', 3500, 'USA'],
            ['Rice', 'Sushi Rice Ukemochi', '2 kg', 450, 'Vietnam'],
            ['Nori', 'Sushi Nori Gold 50 Sheets', '140 g', 650, 'China'],
            ['Nori', 'Sushi Nori Matsu 50 Sheets', '140 g', 900],
            ['Nori', 'Nori Sheet 3Cut 30 Sheets', '30 sheets', 500],
            ['Nori', 'Sushi Nori Gold 10 Sheets', '28 g', 200, 'China'],
            ['Nori', 'Aonori 100g', '100 g', 350],
            ['Vinegar', 'Sushi Vinegar Mizkan Shiragiku', '20 L', 4500],
            ['Vinegar', 'Sushi Vinegar Mizkan Suehiro', '20 L', 4200],
            ['Vinegar', 'Sushi & Rice Vinegar Ukemochi', '1.8 L', 450, 'China'],
            ['Mirin', 'Hon Mirin King 20L', '20 L', 5000],
            ['Mirin', 'Hon Mirin & Sake King', '1.8 L', 850],
            ['Mirin', 'Hon Mirin & Sake Ukemochi', '1.8 L', 550, 'China'],
            ['Sauce', 'Cooking Sauce Mirin Honteri', '1 L', 650],
            ['Vinegar', 'Rice Vinegar Tamanoi 20L', '20 L', 4800],
            ['Dashi', 'Dashino Moto Hondashi Shimaya', '1 kg', 1200],
            ['Dashi', 'Dashino Moto Hondashi China', '1 kg', 800, 'China'],
            ['Dashi', 'Hondashi Powder Ajinomoto', '1 kg', 1400],
            ['Dashi', 'Kombu Dashi Powder Veg', '1 kg', 1300],
            ['Sauce', 'Shiro Dashi Yamashin', '1.8 L', 900],
            ['Soy Sauce', 'White Soy Sauce Yamashin', '1.8 L', 850],
            ['Miso', 'Miso Paste Shiro/Red', '1 kg', 500, 'China'],
            ['Miso', 'Miso Paste Mikochan Shiro', '1 kg', 750],
            ['Miso', 'Miso Paste Mikochan Aka', '1 kg', 750],
            ['Miso', 'Saikyo Miso', '2 kg', 1800],
            ['Noodle', 'Sanuki Udon Marukin 400g', '400 g', 350],
            ['Noodle', 'Instant Nama Udon 180g', '180 g', 150],
            ['Noodle', 'Konjac Shirataki', '200 g', 250],
            ['Noodle', 'Fresh Ramen 180g', '180 g', 180, 'China'],
            ['Noodle', 'Vermicelli', '180 g', 120, 'Korea'],
            ['Noodle', 'Glass Noodle Double Tiger', '500 g', 200, 'Thailand'],
            ['Noodle', 'Chukamen 500g', '500 g', 320],
            ['Sauce', 'Tonkatsu Sauce Bulldog', '1.8 L', 900],
            ['Sauce', 'Tamari Sauce Morita', '1.8 L', 850],
            ['Sauce', 'Yakitori Sauce Ebara', '1.8 L', 800],
            ['Sauce', 'Kabayaki Unagi Sauce', '1.8 L', 900],
            ['Sauce', 'Tsuyu No Moto Sauce', '1.8 L', 750],
            ['Sauce', 'Mentsuyu Yamaki', '1.8 L', 800],
            ['Seasoning', 'Shichimi Togarashi S&B', '300 g', 650],
            ['Seasoning', 'Furikake Seasoning', '500 g', 550],
            ['Seasoning', 'Yukari Furikake Mishima', '200 g', 400],
            ['Curry', 'Vermont Curry House Foods', '1 kg', 750],
            ['Curry', 'Golden Curry S&B', '220 g', 350],
            ['Pickle', 'Pickled Ginger Natural', '1.5 kg', 400, 'Thailand'],
            ['Pickle', 'Pickled Ginger Pink', '1.5 kg', 400, 'Thailand'],
            ['Pickle', 'Beni Shoga Pickle', '1 kg', 500],
            ['Pickle', 'Shibazuke Pickle', '1 kg', 480],
            ['Pickle', 'Pariko Pickle Cucumber', '1 kg', 460],
            ['Pickle', 'Fukujinzuke Pickle', '1 kg', 450],
            ['Pickle', 'Pickled Plum Umeboshi', '1 kg', 800],
            ['Oil', 'Sesame Oil Kadoya', '1.65 L', 1200],
            ['Oil', 'Sesame Oil Double Dragon', '630 ml', 450, 'Thailand'],
            ['Oil', 'White Truffle Oil Urbani', '250 ml', 1800, 'China'],
            ['Mayonnaise', 'Kewpie Mayonnaise', '450 ml', 500],
            ['Mayonnaise', 'Kenko Mayonnaise Plain', '500 g', 420],
            ['Paste', 'Atari Goma Sesame Paste', '300 g', 550],
            ['Dressing', 'Sesame Salad Dressing Kenko', '1 L', 650],
            ['Dressing', 'Sesame Salad Dressing Kewpie', '1 L', 700],
            ['Tofu', 'Tofu Silken Viola', '345 g', 250, 'USA'],
            ['Tofu', 'Tofu Silken Morinaga', '349 g', 280, 'USA'],
            ['Tea', 'Japanese Green Tea Matcha', '1 kg', 2500],
            ['Tempura', 'Tempura Powder Showa', '700 g', 400],
            ['Tempura', 'Tempura Powder Welna', '700 g', 300, 'China'],
            ['Panko', 'Panko Bread Crumbs', '1 kg', 350, 'China'],
            ['Wasabi', 'Wasabi Powder', '1 kg', 800],
            ['Wasabi', 'Wasabi Tube 43g', '43 g', 150],
            ['Yuzu', 'Yuzu Juice 720ml', '720 ml', 1200],
            ['Yuzu', 'Yuzu Juice 1.8L', '1.8 L', 2500],
            ['Yuzu', 'Yuzu Kosho Paste', '50 g', 400],
            ['Soy Sauce', 'Soy Sauce Kikkoman', '1 L', 450],
            ['Soy Sauce', 'Soy Sauce Kikkoman 10L', '10 L', 3500],
            ['Soy Sauce', 'Kikkoman Dark Soy Sauce', '900 ml', 400],
            ['Soy Sauce', 'Soy Sauce Yamasha Less Salt 18L', '18 L', 4000],
            ['Soy Sauce', 'Soy Sauce Yamasha Regular 18L', '18 L', 3800],
            ['Sauce', 'Oyster Sauce Kikkoman', '2.46 kg', 800],
            ['Sauce', 'Oyster Sauce Panda LKK', '2.2 kg', 650, 'Malaysia'],
            ['Sauce', 'Chilli Bean Sauce LKK', '2.4 kg', 700, 'China'],
            ['Sauce', 'Kimchee Base Sauce', '1 L', 550],
            ['Sauce', 'Sriracha Chilli Sauce', '481 ml', 250, 'Thailand'],
            ['Sauce', 'Sweet Chilli Sauce Maepranom', '980 ml', 300, 'China'],
            ['Paste', 'Gochujang Paste Daesang', '500 g', 400, 'Korea'],
            ['Paste', 'Soy Bean Paste Daesang', '1 kg', 500, 'Korea'],
            ['Paste', 'Tobanjan Youki', '1 kg', 650],
            ['Seasoning', 'Knorr Chicken Seasoning', '1 kg', 450, 'Thailand'],
            ['Rice Paper', 'Rice Paper Ukemochi', '400 g', 250, 'Thailand'],
            ['Starch', 'Potato Starch Windmill', '500 g', 200],
            ['Starch', 'Wheat Starch Ukemochi', '25 kg', 2500, 'China'],
            ['Flour', 'Red Lotus Flour', '1 kg', 180, 'Thailand'],
            ['Flour', 'Erawan Rice Flour', '1 kg', 200, 'Thailand'],
            ['Mushroom', 'Shiitake Mushroom Dried', '1 kg', 1200, 'China'],
            ['Mushroom', 'Black Fungus', '500 g', 300, 'Thailand'],
            ['Canned', 'Bamboo Shoots Canned', '507 g', 200, 'China'],
            ['Canned', 'Water Chestnut In Water', '507 g', 220, 'China'],
            ['Canned', 'Sweet Corn Habbit', '410 g', 180, 'China'],
            ['Marinade', 'Bulgogi Marinade Jin', '2 kg', 1200, 'Korea'],
            ['Inari', 'Inari 40 Pcs', '1 kg', 650],
            ['Coconut', 'Coconut Milk Chaokoh', '400 ml', 180, 'Thailand'],
            ['Seaweed', 'Wakame Dried', '500 g', 600],
            ['Seaweed', 'Kaiso Salad Mix Dried', '100 g', 350],
            ['Bonito', 'Katsuo Bushi Bonito Flakes', '500 g', 900]
        ]
    },
    'japanese-frozen-seafood': {
        img: 'pictures/landing_img2.png',
        country: 'Japan',
        items: [
            ['Tuna', 'Bluefin Tuna Akami', '200-400 g', 5500],
            ['Tuna', 'Bluefin Tuna Chutoro', '200-400 g', 7500],
            ['Tuna', 'Bluefin Tuna Otoro', '200-400 g', 9000],
            ['Uni', 'Sea Urchin Uni', '100 g', 3500],
            ['Fish', 'Hamachi Fillet Yellowtail', '1.9-2.3 kg', 4500],
            ['Fish', 'Hamachi Loin Yellowtail', '500-900 g', 3500],
            ['Fish', 'Kampachi Fillet Amberjack', '1-2 kg', 4000],
            ['Fish', 'Octopus Boiled', '1-1.5 kg', 2500],
            ['Scallops', 'Hotate Scallops Hokkaido 31-35', '31-35 pcs', 3200],
            ['Scallops', 'Hotate Scallops USA 31-35', '31-35 pcs', 2800, 'USA'],
            ['Scallops', 'Hotate Scallops Hokkaido 20-25', '20-25 pcs', 3800],
            ['Roe', 'Ikura Salmon Roe', '500 g', 4500],
            ['Wasabi', 'Wasabi Tube Kaneku 505', '750 g', 1200],
            ['Wasabi', 'Kizami Wasabi', '150 g', 650],
            ['Citrus', 'Kizami Yuzu Zest', '100 g', 500],
            ['Roe', 'Frozen Mentaiko Tube', '500 g', 2200],
            ['Prawns', 'Amaebi Sweet Prawns 48pc', '115 g', 1500],
            ['Prawns', 'Sushi Shrimp Boiled 20pc', '20 pcs', 1200],
            ['Roe', 'Tobikko Orange Flying Fish Roe', '500 g', 2500],
            ['Roe', 'Tobikko Green Flying Fish Roe', '500 g', 2500],
            ['Roe', 'Tobikko Black Flying Fish Roe', '500 g', 2500],
            ['Fish', 'Unagi Kabayaki Grilled Eel', '250 g', 1800, 'Thailand'],
            ['Fish', 'Shimesaba Vinegared Mackerel', '120 g', 650, 'Thailand'],
            ['Seaweed', 'Frozen Chuka Wakame', '2 kg', 800, 'Thailand'],
            ['Wrapper', 'Happy Belly Gyoza Sheet 30pc', '300 g', 250, 'Singapore'],
            ['Wrapper', 'TYJ Wonton Sheets 30pc', '300 g', 220, 'Singapore'],
            ['Wrapper', 'TYJ Spring Roll Sheet 190', '300 g', 230, 'Singapore'],
            ['Wrapper', 'TYJ Bao Bun Lotus Leaf 10pc', '10 pcs', 280, 'Vietnam'],
            ['Crab', 'Soft Shell Crab', '80-120 g/pc', 1800, 'India'],
            ['Fish', 'Frozen Basa Fillet Imported', '1 kg', 550, 'Vietnam'],
            ['Fish', 'Frozen Basa Fillet Indian', '1 kg', 480, 'India'],
            ['Fish', 'Frozen John Dory Fillet', '1 kg', 1600, 'Vietnam'],
            ['Soy', 'Natto Fermented Soya Bean', '40 g', 200],
            ['Beans', 'Edamame Green Soybeans', '500 g', 350, 'Indonesia'],
            ['Beans', 'Edamame Green Soybeans Peeled', '500 g', 400, 'Indonesia'],
            ['Salmon', 'Salmon Fresh With Head', '4-6 kg', 3500, 'Norway'],
            ['Salmon', 'Salmon Fillet Sushi Grade', '1-1.5 kg', 2800, 'Norway'],
            ['Salmon', 'Salmon Fillet Sushi Premium', '1-1.5 kg', 3200, 'Norway'],
            ['Salmon', 'Salmon Fillet Smoked Premium', '1-1.4 kg', 3500, 'Norway'],
            ['Tuna', 'Yellowfin Tuna Saku AAA', '200-400 g', 2200, 'India'],
            ['Tuna', 'Yellowfin Tuna Saku Vietnam', '200-400 g', 2000, 'Vietnam'],
            ['Tuna', 'Yellowfin Tuna Loin', '3-7 kg', 2500, 'India'],
            ['Fish', 'Frozen Black Cod Head Off', '2-3 kg', 3500, 'USA'],
            ['Fish', 'Chilean Seabass Frozen', '4-8 kg', 4500, 'USA'],
            ['Crab', 'Imitation Crab Sticks 9cm', '500 g', 350, 'India'],
            ['Crab', 'Imitation Crab Sticks 7.5cm', '1 kg', 600, 'India'],
            ['Crab', 'Crab Meat Medium Chilled', '454 g', 1800, 'India'],
            ['Crab', 'Crab Meat Jumbo Chilled', '454 g', 2200, 'India'],
            ['Noodle', 'Frozen Udon Noodle 250x5g', '1.25 kg', 550],
            ['Fish', 'Fish Cake Naruto', '120 g', 300],
            ['Prawns', 'Nobashi Prawns 20pc', '270 g', 650, 'India']
        ]
    },
    'golden-wrap': {
        img: 'pictures/landing_img2.png',
        country: 'China',
        items: [
            ['Dough Sheet', 'GW Gyoza Skin Dough Sheet', '300 g', 220],
            ['Dough Sheet', 'GW Spring Roll Sheet 10"', '550 g', 280],
            ['Dough Sheet', 'GW Spring Roll Sheet 7.5"', '550 g', 270],
            ['Dough Sheet', 'GW Spring Roll Sheet 8.5"', '550 g', 275],
            ['Dough Sheet', 'GW Wonton Skin Dough Sheet', '300 g', 220],
            ['Bun', 'GW Lotus Leaf Bun', '400 g', 300]
        ]
    },
    'sakura-frozen': {
        img: 'pictures/landing_img2.png',
        country: 'Japan',
        items: [
            ['Frozen', 'Sakura Edamame In Pod', '500 g', 350, 'Indonesia'],
            ['Frozen', 'Sakura Edamame Without Pod', '500 g', 380, 'Indonesia'],
            ['Frozen', 'Sakura Frozen Noodle', '40 g', 120],
            ['Frozen', 'Sakura Frozen Wasabi Paste 750g', '750 g', 550]
        ]
    }
};

// Expand compact data into full product catalog
// imgBase allows each page to set the correct relative path prefix
const imgBase = typeof PRODUCT_IMG_BASE !== 'undefined' ? PRODUCT_IMG_BASE : '';
const productCatalog = [];

// Build fallback catalog from hardcoded data
function _buildFallbackCatalog() {
    let counter = 0;
    for (const [category, data] of Object.entries(productData)) {
        for (const item of data.items) {
            counter++;
            productCatalog.push({
                id: item[1].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '') + '-' + counter,
                category,
                classification: item[0],
                country: item[4] || data.country,
                name: item[1],
                weight: item[2],
                price: item[3],
                image: imgBase + data.img,
                status: item[5] || 'in-stock'
            });
        }
    }
}

// Fetch products from the database (primary source)
const _apiBase = window.BASE_URL || '';

const productsReady = fetch(_apiBase + '/api/products')
    .then(res => res.ok ? res.json() : Promise.reject())
    .then(dbProducts => {
        dbProducts.forEach(p => {
            productCatalog.push({
                id: p.code.toLowerCase(),
                category: p.category,
                classification: p.classification || '',
                country: p.country || 'India',
                name: p.name,
                weight: p.weight || '',
                price: p.price,
                image: imgBase + (p.image || ''),
                status: p.status || 'in-stock'
            });
        });
    })
    .catch(() => {
        // Fallback to hardcoded data if API is unavailable
        if (productCatalog.length === 0) {
            _buildFallbackCatalog();
        }
    });
